### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by vasukiran** [sitevalidator/accessibility#1]
Hi 
 I am getting this below error
irb(main):001:0> require 'accessibility'
=> true
irb(main):002:0> a11y = Accessibility.check('http://validationhell.com')
=> #<Accessibility::Checker:0x3bf3a90 @url="http://validationhell.com", @checker_uri="https://access-lint-server-demo.herokuapp.com", @audit=#<Accessibility::Audit:0x3bf39e8 @checker=#<Accessibility::Checker:0x3bf3a90 ...>>>
irb(main):003:0> warning = a11y.warnings.last
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:921:in `connect'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:921:in`block in connect'
        from C:/Ruby200/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:921:in`connect'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:851:in`start'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:1373:in `request'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/httparty-0.13.5/lib/httparty/request.rb:101:in`perform'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/httparty-0.13.5/lib/httparty.rb:522:in `perform_request'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/httparty-0.13.5/lib/httparty.rb:460:in`get'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/httparty-0.13.5/lib/httparty.rb:560:in `get'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/accessibility-0.1.0/lib/accessibility/checker.rb:47:in`raw'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/accessibility-0.1.0/lib/accessibility/audit.rb:22:in `all'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/accessibility-0.1.0/lib/accessibility/audit.rb:37:in`failed'
        from C:/Ruby200/lib/ruby/gems/2.0.0/gems/accessibility-0.1.0/lib/accessibility/audit.rb:47:in `warnings'
        from (irb):3
        from C:/Ruby200/bin/irb:12:in`<main>'irb(main):004:0>

**Comment by Anagha22** [comment]
In your Gemfile,change the https://rubygems.org to http://rubygems.org and run. This should fix the SSL error.
